### ISSUE TITLE
Support custom terminal filetype?

### ISSUE THREAD

**Issue by lkhphuc** [romainchapou/nostalgic-term.nvim#1]
Hi, thank for the plugin.

I see that current this plugin is only activated for `filetype==""`.
It would be nice if I can configure `enabled_filetypes` for custom plugin filetype, for example [toggleterm.nvim](https://github.com/akinsho/toggleterm.nvim) .

**Comment by romainchapou** [comment]
Hi, glad you found the plugin useful!

This is clearly a good idea and that's easy to implement. I need to do a bit of testing, but expect an update soon. I'm also thinking about adding toggleterm support by default as I know it is a pretty popular plugin, but I'm not sure if it's completely doable as it seems a setting must be set in toggleterm's setup function for the two plugins to be really compatible. I'll look into that.

**Comment by romainchapou** [comment]
The update is pushed. As you proposed, you will have to add `"toggleterm"` in the new `enabled_filetypes` option. You should also set toggleterm's `start_in_insert` option to false as explained in the readme.
